import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "../shared";
export const metadata: Metadata = { title: "Support", description: "Get help with SVNLY, safety, purchases, privacy and account deletion." };

export default function Support() { return <LegalPage eyebrow="HELP · SUPPORT" title="How can we help?" updated="20 August 2026">
  <div className="support-cards"><div><strong>Secure in-app support</strong><p>SVNLY → Profile → Settings → Help &amp; Contact Support. This creates an authenticated ticket without exposing account details by email.</p></div><Link href="/account-deletion"><strong>Delete your account</strong><p>Start deletion directly in the app or read the exact process.</p></Link><Link href="/community"><strong>Report or block</strong><p>Use the three-dot Safety action on a take or comment for immediate in-app controls.</p></Link><div><strong>Purchases</strong><p>Settings → SVNLY Plus → Restore Purchases. Manage renewals in your Apple subscriptions.</p></div></div>
  <section><h2>Common questions</h2><h3>Why can’t I see the feed?</h3><p>The daily feed unlocks only after your own valid take. This rule applies to everyone. A take under moderation still unlocks the feed.</p><h3>Can I retake?</h3><p>No voluntary retakes. The server may grant at most two retries only after a verified camera, file or upload failure and when no valid take exists.</p><h3>My upload is offline</h3><p>Your protected pending take remains on your iPhone and resumes automatically after connectivity returns or the app restarts. You cannot start another take while it is pending.</p><h3>How do I appeal moderation?</h3><p>Open the moderation notice inside SVNLY and choose Appeal. Include context, not passwords or sensitive identity documents.</p><h3>Public support contact</h3><p>A public support email and complete legal postal address must be confirmed by the owner before the App Store launch. Until then, authenticated in-app support is the official channel.</p></section>
  <section className="lang-break"><p className="eyebrow">DEUTSCH</p><h2>Support</h2><p>Öffne in SVNLY: Profil → Einstellungen → Hilfe &amp; Support kontaktieren. Dort entsteht ein sicher authentifiziertes Ticket. Inhalte und Nutzer meldest oder blockierst du direkt über die Safety-Aktion. Käufe stellst du unter SVNLY Plus wieder her und verwaltest sie in deinen Apple-Abonnements.</p><h3>Feed gesperrt?</h3><p>Der Tagesfeed wird erst nach deinem gültigen Take freigeschaltet. Ein Take in Moderation reicht zur Freischaltung.</p><h3>Wiederholung?</h3><p>Keine freiwilligen Retakes. Maximal zwei technische Retries gibt es nur nach einem verifizierten Fehler und wenn kein gültiger Take existiert.</p><h3>Öffentlicher Kontakt</h3><p>Support-E-Mail und vollständige postalische Pflichtangaben werden vom Eigentümer vor dem App-Store-Start bestätigt. Bis dahin ist der authentifizierte In-App-Support der offizielle Kanal.</p></section>
  </LegalPage>; }
