import type { Metadata } from "next";
import { LegalPage } from "../shared";
export const metadata: Metadata = { title: "Privacy Policy", description: "How SVNLY collects, uses, protects and deletes personal data." };

export default function Privacy() {
  return <LegalPage eyebrow="PRIVACY · DATENSCHUTZ" title="Privacy Policy" updated="20 August 2026">
    <section><h2>1. Who is responsible</h2><p>SVNLY is operated by Sebastian Bürgy in Switzerland. The complete postal contact and public support address will be added before public launch. Inside the app, signed-in users can contact support under Settings → Help &amp; Contact Support.</p>
    <h2>2. Data we process</h2><p><strong>Account:</strong> email address or Apple account token, internal user ID and authentication events. <strong>Profile:</strong> username, display name, country, language, time zone, optional avatar and bio, visibility and comment preferences. <strong>Eligibility:</strong> private date of birth and policy acceptances to enforce the 16+ minimum age.</p><p><strong>Content:</strong> seven-second videos, audio, thumbnails, comments, reactions, follows, blocks, reports and moderation appeals. <strong>Operations:</strong> upload attempts, technical-failure diagnostics, push token, purchase entitlement, support tickets, security logs and content-free first-party analytics.</p>
    <h2>3. Why</h2><p>We process data to provide authentication, the daily challenge, one-take enforcement, uploads, private media delivery, feeds, social features, rankings, streaks, purchases, notifications, support, safety, fraud prevention and legal compliance. We do not sell personal data or use advertising tracking.</p>
    <h2>4. Storage and recipients</h2><p>Application data is stored with Supabase infrastructure selected for SVNLY. Purchases are handled by Apple and RevenueCat. Where enabled, OpenAI processes limited moderation inputs server-side; API keys never enter the app. Service providers receive only the data required for their function under contractual safeguards.</p>
    <h2>5. Visibility</h2><p>Signed-in users may see public profiles and published takes after participating. Private profiles are visible only to accepted followers. Country and World feeds exclude private accounts. Birth date, email, device tokens, reports, moderation records and support tickets are never public.</p>
    <h2>6. Retention and deletion</h2><p>Users can delete individual takes and start complete account deletion inside the app. Account deletion locks the account immediately and removes or anonymizes profile data, media, interactions, device tokens and person-linked analytics. Minimal anonymized safety evidence may remain where necessary for legal claims or abuse prevention. Protected pending-upload files are deleted after successful upload.</p>
    <h2>7. Your choices and rights</h2><p>You can edit profile and privacy settings, manage notifications, block users, delete content, restore purchases and delete your account. Subject to applicable law, you may request access, correction, portability, restriction or objection through the in-app support channel.</p>
    <h2>8. Data we do not collect</h2><p>SVNLY does not request precise GPS coordinates, address books, advertising IDs, face templates, biometric identification or unnecessary device identifiers. We remove unnecessary media metadata and do not use ATT while no tracking occurs.</p>
    <h2>9. Security and children</h2><p>SVNLY uses row-level authorization, private storage, short-lived links, server-side time, rate limits, audit logs and least-privilege credentials. The service is for people aged 16 or older; under-16 registrations are rejected.</p>
    <h2>10. Changes</h2><p>Material changes are versioned and communicated in the app. New consent is requested when legally required.</p></section>
    <section className="lang-break"><p className="eyebrow">DEUTSCH</p><h2>Datenschutzerklärung</h2><p>SVNLY wird von Sebastian Bürgy in der Schweiz betrieben. Vollständige postalische Kontaktdaten und eine öffentliche Support-Adresse werden vor dem öffentlichen Start ergänzt. Angemeldete Nutzer erreichen den Support direkt in der App.</p><h3>Welche Daten und wofür?</h3><p>Wir verarbeiten Konto- und Profildaten, ein privates Geburtsdatum zur Altersprüfung ab 16 Jahren, Videos und Ton, Kommentare, Reactions, Follow-/Block-/Meldedaten, technische Uploaddiagnosen, Push-Token, Kaufberechtigungen und datensparsame First-Party-Analytics. Das dient ausschliesslich der App-Funktion, Sicherheit, Moderation, Abrechnung, Support und rechtlichen Pflichten. Wir verkaufen keine Daten und betreiben kein Werbetracking.</p><h3>Sichtbarkeit und Speicherung</h3><p>Öffentliche Profile und freigegebene Takes sind nach eigener Teilnahme für angemeldete Nutzer sichtbar. Private Profile sind nur für bestätigte Follower sichtbar. E-Mail, Geburtsdatum, Tokens, Meldungen und Moderationsdaten sind nicht öffentlich. Supabase speichert die App-Daten; Apple und RevenueCat verarbeiten Käufe. OpenAI kann – falls aktiviert – begrenzte Moderationsinhalte ausschliesslich serverseitig prüfen.</p><h3>Löschung und Rechte</h3><p>Takes und das gesamte Konto können in der App gelöscht werden. Die Kontolöschung sperrt das Konto sofort und löscht oder anonymisiert personenbezogene Daten, Medien, Interaktionen und Tokens. Minimal anonymisierte Sicherheitsnachweise können bei rechtlicher Notwendigkeit verbleiben. Nutzer können Auskunft, Berichtigung, Übertragung, Einschränkung oder Widerspruch über den In-App-Support verlangen.</p><h3>Nicht erhobene Daten</h3><p>Keine genauen GPS-Koordinaten, Kontakte, Werbe-ID, Gesichtsvorlagen oder biometrische Identifikation. Unnötige Medienmetadaten werden entfernt. Unter 16-Jährige sind nicht zugelassen.</p></section>
  </LegalPage>;
}
