import type { Metadata } from "next";
import { LegalPage } from "../shared";
export const metadata: Metadata = { title: "Account Deletion", description: "How to permanently delete a SVNLY account and personal data." };

export default function DeleteAccount() { return <LegalPage eyebrow="ACCOUNT · KONTO" title="Delete your account" updated="20 August 2026">
  <div className="callout"><strong>Deletion starts inside the app.</strong><p>SVNLY → Profile → Settings → Delete Account → type DELETE → confirm. An email request is not the only deletion route.</p></div>
  <section><h2>What happens</h2><ol><li>Your account is marked for deletion and access is locked immediately.</li><li>Active sessions end.</li><li>A protected server job removes or anonymizes profile and age data, avatars, takes, thumbnails, comments, reactions, follows, blocks, device tokens, notifications, person-linked analytics and support data without a retention duty.</li><li>The authentication user is deleted and completion is recorded without retaining the deleted profile.</li></ol><h2>What may remain</h2><p>Minimal anonymized moderation or security evidence may remain only where needed to meet legal duties, defend claims or prevent serious abuse. It is not kept as an active profile and is access-restricted.</p><h2>Before deleting</h2><p>Cancel an active Apple subscription separately in Apple account settings; deleting the account does not cancel App Store billing. Save anything you need first. Deletion cannot be used to obtain another take for the same challenge date.</p></section>
  <section className="lang-break"><p className="eyebrow">DEUTSCH</p><h2>Konto löschen</h2><p>Öffne SVNLY → Profil → Einstellungen → Konto löschen → tippe DELETE → bestätigen. Das Konto wird sofort gesperrt, Sessions werden beendet und ein geschützter Serverjob löscht oder anonymisiert Profil-, Alters-, Medien-, Kommentar-, Reaction-, Follow-, Block-, Token-, Benachrichtigungs-, Analyse- und Supportdaten.</p><p>Minimal anonymisierte Moderations- oder Sicherheitsnachweise bleiben nur bei rechtlicher Notwendigkeit. Ein Apple-Abonnement muss separat in den Apple-Kontoeinstellungen gekündigt werden. Die Löschung ermöglicht keinen neuen Take für denselben Challenge-Tag.</p></section>
  </LegalPage>; }
