import type { Metadata } from "next";
import { LegalPage } from "../shared";
export const metadata: Metadata = { title: "Community Guidelines", description: "SVNLY safety and community standards in English and German." };

export default function Community() { return <LegalPage eyebrow="COMMUNITY · SICHERHEIT" title="Community Guidelines" updated="20 August 2026">
  <div className="callout"><strong>Be real. Be safe. Be kind.</strong><p>If someone is in immediate danger, contact local emergency services. In-app reporting is not an emergency service.</p></div>
  <section><h2>What belongs here</h2><p>Spontaneous, safe and lawful moments that answer the daily challenge. Respect people who appear in your take. Ask permission where appropriate and choose another subject if recording could expose someone’s private life.</p><h2>Not allowed</h2><h3>Minor safety and sexual content</h3><p>No sexual content, grooming, exploitation, nudity, sexualisation of minors or requests that put minors at risk. Never share identifying school, home or schedule information about a minor.</p><h3>Violence and dangerous activity</h3><p>No threats, graphic harm, encouragement of self-harm, weapons misuse, dangerous driving, unsafe heights, fire stunts, illegal challenges or pressure to perform risky acts.</p><h3>Hate and harassment</h3><p>No attacks or exclusion based on protected traits, dehumanisation, slurs, bullying, stalking, coordinated harassment, unwanted sexual attention or celebration of violence.</p><h3>Privacy and authenticity</h3><p>No addresses, identity documents, financial details, intimate imagery, doxxing, impersonation, face swaps or deceptive AI-generated people. Live looks may change color and texture only; they must not reshape faces or bodies.</p><h3>Spam, fraud and rights</h3><p>No scams, malware, repetitive promotion, fake engagement, bot activity, copyright infringement or attempts to manipulate retries, views, reactions, comments or rankings.</p><h2>Enforcement</h2><p>SVNLY can limit distribution, place content under review, remove content, issue warnings, restrict features or suspend/ban accounts. Decisions consider severity, context, history and risk. Users can report takes, comments and profiles, block immediately, and appeal eligible decisions.</p></section>
  <section className="lang-break"><p className="eyebrow">DEUTSCH</p><h2>Community-Richtlinien</h2><p>Teile spontane, sichere und rechtmässige Momente. Respektiere gefilmte Personen und hole nötige Einwilligungen ein. Bei akuter Gefahr kontaktiere lokale Notfalldienste; die In-App-Meldung ist kein Notfalldienst.</p><h3>Nicht erlaubt</h3><p>Sexuelle Inhalte, Grooming, Ausbeutung oder Gefährdung Minderjähriger; Gewalt, Drohungen, Selbstverletzungsförderung, Waffenmissbrauch oder riskante Challenges; Hass, Diskriminierung, Mobbing, Stalking oder koordinierte Belästigung; Adressen, Dokumente, Finanzdaten, intime Bilder, Doxxing oder Identitätsmissbrauch; Betrug, Spam, Bots, Urheberrechtsverletzungen sowie Manipulation von Attempts, Views, Reactions, Kommentaren oder Rankings.</p><h3>Authentizität und Durchsetzung</h3><p>Live Looks dürfen Farben und Texturen verändern, aber keine Gesichter oder Körper formen. SVNLY kann Inhalte prüfen, zurückhalten oder entfernen, Funktionen einschränken und Konten verwarnen, sperren oder bannen. Meldung, sofortige Blockierung und Einspruch stehen zur Verfügung.</p></section>
  </LegalPage>; }
